### ISSUE TITLE
Rendu Exam 1

### ISSUE THREAD

**Issue by BPTdev** [BPTdev/GPR1-SocialNetwork#1]
Rendu pour @NicolasGlassey 

Le test `test_constructor_InstantiationWithDuplicatedSubscribers_ThrowsException()` ne passe pas car je n'arrive pas à déterminer que les objet du tableau sont unique. 
Soit php les considère tous comme unique donc les 16.
Soit il considère que ce sont tous le même objet (ce qui est vrai, mais le contenu est différent) et il ne garde que le premier.

Le test `test_unsubscribe_NominalCase_Success` ne passe pas car il entre en comflit avec un autre test `test_unsubscribe_EmptyListOfSubscriber_ThrowsException`.

Le commit à prendre est celui ci :  [5269c006da4d40e37ad678320fdb383bcdd2a41b](https://github.com/BPTdev/GPR1-SocialNetwork/commit/5269c006da4d40e37ad678320fdb383bcdd2a41b)

**Comment by NicolasGlassey** [comment]
@BPTdev 

Bonjour Benoit,

J'ai bien pris en compte cette issue pour l'évaluation de votre examen.

Bonne suite de week-end !
